import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/pages/_home.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <hero>
          <div className="column">
            <h1>4788</h1>
            <h2>4788</h2>
            <p>4788</p>
            <p><a href="./">4788</a></p>
          </div>
        </hero>
      </div>
    </>
  )
}
