import Head from 'next/head'
import Image from 'next/image'
import { Arrows, Logo } from '@/components/Icons'
import Marquee from 'react-fast-marquee'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <hero-no-padding>
          <div className="column">
            <Marquee speed={25} gradient={false}>
              <h1-ticker>4788//Can&apos;t Control//</h1-ticker>
            </Marquee>
            <Arrows className="arrows" />
          </div>
        </hero-no-padding>
        <heros>
          <h2>More Content</h2>
          <h2>More Content</h2>
          <h2>More Content</h2>
          <h2>More Content</h2>
        </heros>
      </div>
    </>
  )
}
