import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Robots | 4788</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="page">
        <hero-no-padding>
          <div className="column">
          </div>
        </hero-no-padding>
        <heros>
        </heros>
      </div>
    </>
  )
}
