name: Build-Checks

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Ubuntu-Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: pnpm install
    - name: Lint
      run: pnpm run lint
    - name: Build
      run: pnpm run build

  Windows-Build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: pnpm install
    - name: Lint
      run: pnpm run lint
    - name: Build
      run: pnpm run build

  MacOS-Build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: pnpm install
    - name: Lint
      run: pnpm run lint
    - name: Build
      run: pnpm run build
